{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "from collections import OrderedDict\n",
    "# from romslab import zlevs\n",
    "from glob import glob\n",
    "from netCDF4 import Dataset\n",
    "from datetime import datetime\n",
    "\n",
    "import multiprocessing as mp\n",
    "\n",
    "#from zlevs.py\n",
    "def csf(sc, theta_s,theta_b):\n",
    "#######################################################################\n",
    "#\n",
    "#  function h = csf(sc, theta_s,theta_b);\n",
    "#\n",
    "#  Further Information:\n",
    "#  http://www.brest.ird.fr/Roms_tools/\n",
    "#\n",
    "#  This file is part of ROMSTOOLS\n",
    "#\n",
    "#  ROMSTOOLS is free software; you can redistribute it and/or modify\n",
    "#  it under the terms of the GNU General Public License as published\n",
    "#  by the Free Software Foundation; either version 2 of the License,\n",
    "#  or (at your option) any later version.\n",
    "#\n",
    "#  ROMSTOOLS is distributed in the hope that it will be useful, but\n",
    "#  WITHOUT ANY WARRANTY; without even the implied warranty of\n",
    "#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n",
    "#  GNU General Public License for more details.\n",
    "#\n",
    "#  You should have received a copy of the GNU General Public License\n",
    "#  along with this program; if not, write to the Free Software\n",
    "#  Foundation, Inc., 59 Temple Place, Suite 330, Boston,\n",
    "#  MA  02111-1307  USA\n",
    "#\n",
    "######################################################################\n",
    "\n",
    "    if (theta_s > 0 ):\n",
    "        csrf=(1-np.cosh(sc*theta_s))/(np.cosh(theta_s)-1)\n",
    "    else:\n",
    "        csrf=-sc**2\n",
    "\n",
    "    if (theta_b > 0):\n",
    "        h = (np.exp(theta_b*csrf)-1)/(1-np.exp(-theta_b))\n",
    "    else:\n",
    "        h  = csrf.copy();\n",
    "\n",
    "    return h\n",
    "\n",
    "\n",
    "def zlevs(h,zeta,theta_s,theta_b,hc,N,type='r',vtransform=2):\n",
    "    \"\"\"\n",
    "    ################################################################\n",
    "    #\n",
    "    #  function z = zlevs(h,zeta,theta_s,theta_b,hc,N,type);\n",
    "    #\n",
    "    #  this function compute the depth of rho or w points for ROMS\n",
    "    #\n",
    "    #  On Input:\n",
    "    #\n",
    "    #    type    'r': rho point 'w': w point\n",
    "    #\n",
    "    #  On Output:\n",
    "    #\n",
    "    #    z       Depths (m) of RHO- or W-points (3D matrix).\n",
    "    #\n",
    "    #  Further Information:\n",
    "    #  http://www.brest.ird.fr/Roms_tools/\n",
    "    #\n",
    "    #  This file is part of ROMSTOOLS\n",
    "    #\n",
    "    #  ROMSTOOLS is free software; you can redistribute it and/or modify\n",
    "    #  it under the terms of the GNU General Public License as published\n",
    "    #  by the Free Software Foundation; either version 2 of the License,\n",
    "    #  or (at your option) any later version.\n",
    "    #\n",
    "    #  ROMSTOOLS is distributed in the hope that it will be useful, but\n",
    "    #  WITHOUT ANY WARRANTY; without even the implied warranty of\n",
    "    #  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n",
    "    #  GNU General Public License for more details.\n",
    "    #\n",
    "    #  You should have received a copy of the GNU General Public License\n",
    "    #  along with this program; if not, write to the Free Software\n",
    "    #  Foundation, Inc., 59 Temple Place, Suite 330, Boston,\n",
    "    #  MA  02111-1307  USA\n",
    "    #\n",
    "    #  Copyright (c) 2002-2006 by Pierrick Penven\n",
    "    #  e-mail:Pierrick.Penven@ird.fr\n",
    "    #  Translated to Python by Rafael Soutelino, rsoutelino@gmail.com\n",
    "    #  Last Modification: Aug, 2010\n",
    "    ################################################################\n",
    "    \"\"\"\n",
    "\n",
    "    M, L = h.shape\n",
    "\n",
    "    # Set S-Curves in domain [-1 < sc < 0] at vertical W- and RHO-points.\n",
    "\n",
    "    sc_r=np.zeros(N)\n",
    "    Cs_r=np.zeros(N)\n",
    "    sc_w=np.zeros(N+1)\n",
    "    Cs_w=np.zeros(N+1)\n",
    "\n",
    "    if (vtransform == 2):\n",
    "        ds=1./N;\n",
    "        if type=='w':\n",
    "\n",
    "            sc_w[0] = -1.0\n",
    "            sc_w[-1] =  0\n",
    "            Cs_w[0] = -1.0\n",
    "            Cs_w[-1] =  0\n",
    "\n",
    "            sc_w[1:N] = ds*(np.arange(1,N)-N)\n",
    "            Cs_w = csf(sc_w, theta_s,theta_b)\n",
    "            N+=1\n",
    "    #    Still in matlab code\n",
    "    #    disp(['===================================='])\n",
    "    #    for k=N:-1:1\n",
    "    #        disp(['Niveau S=',num2str(k),' Cs=',num2str( Cs_w(k), '%8.7f')])\n",
    "    #    end\n",
    "    #    disp(['===================================='])\n",
    "\n",
    "        else:\n",
    "\n",
    "            sc = ds*(np.arange(1,N+1)-N-0.5)\n",
    "            Cs_r = csf(sc, theta_s,theta_b)\n",
    "            sc_r = sc.copy()\n",
    "    #    Still in matlab code\n",
    "    #    disp(['===================================='])\n",
    "    #    for k=N:-1:1\n",
    "    #        disp(['Niveau S=',num2str(k),' Cs=',num2str( Cs_r(k), '%8.7f')])\n",
    "    #    end\n",
    "    #    disp(['===================================='])\n",
    "\n",
    "    else:\n",
    "        cff1 = 1.0 / np.sinh( theta_s )\n",
    "        cff2 = 0.5 / np.tanh( 0.5*theta_s )\n",
    "        ##\n",
    "        if type=='w':\n",
    "            sc = ( np.arange(0,N+1) - N ) / N\n",
    "            N  = N + 1\n",
    "        else:\n",
    "            sc = ( np.arange(1,N+1) - N - 0.5 ) / N\n",
    "        ##\n",
    "\n",
    "        Cs = (1 - theta_b) * cff1 * np.sinh( theta_s * sc ) + \\\n",
    "            theta_b * ( cff2 * np.tanh(theta_s *(sc + 0.5) ) - 0.5 )\n",
    "\n",
    "    #   Still in matlab code\n",
    "    #    disp(['===================================='])\n",
    "    #    for k=N:-1:1\n",
    "    #        disp(['Niveau S=',num2str(k),' Cs=',num2str( Cs(k), '%8.7f')])\n",
    "    #    end\n",
    "    #    disp(['===================================='])\n",
    "\n",
    "    # ------------------------------------------------------------------ #\n",
    "\n",
    "    # Create S-coordinate system: based on model topography h(i,j),\n",
    "    # fast-time-averaged free-surface field and vertical coordinate\n",
    "    # transformation metrics compute evolving depths of of the three-\n",
    "    # dimensional model grid. Also adjust zeta for dry cells.\n",
    "\n",
    "    Dcrit = 0.2 # min water depth in dry cells\n",
    "    h[h==0] = 1e-14\n",
    "    zeta[zeta<(Dcrit-h)] = Dcrit - h[zeta<(Dcrit-h)]\n",
    "    hinv = 1./h\n",
    "    z = np.zeros([N,M,L])\n",
    "\n",
    "    if (vtransform == 2):\n",
    "\n",
    "        if type=='w':\n",
    "            cff1 = Cs_w.copy()\n",
    "            cff2 = sc_w.copy() + 1\n",
    "            sc = sc_w.copy()\n",
    "        else:\n",
    "            cff1 = Cs_r.copy()\n",
    "            cff2 = sc_r.copy() + 1\n",
    "            sc = sc_r.copy()\n",
    "\n",
    "        h2 = h + hc\n",
    "        cff = hc*sc\n",
    "        h2inv = 1./h2\n",
    "\n",
    "        for k in np.arange(0,N):\n",
    "            z0 = cff[k] + cff1[k]*h\n",
    "            z[k,:,:] = (z0*h)/h2 + zeta*(1.+ z0*h2inv)\n",
    "\n",
    "    else:\n",
    "\n",
    "        cff1 = Cs.copy()\n",
    "        cff2 = sc + 1\n",
    "        cff = hc*(sc-Cs)\n",
    "\n",
    "        for k in range(0, N):\n",
    "            z0         = cff[k] + cff1[k]*h\n",
    "            z[k,:,:] = z0 + zeta*( 1 + z0*hinv )\n",
    "\n",
    "    return z\n",
    "\n",
    "\n",
    "### FUNCTION UVW2RHO_3D ##################################################\n",
    "def uvw2rho_3d(ufield,vfield,wfield):\n",
    "\n",
    "    \"\"\"\n",
    "    ################################################################\n",
    "    #\n",
    "    #   compute the values of u,v at t,s points ...\n",
    "    #\n",
    "    #   adptation of the w matrix\n",
    "    #\n",
    "    #   Dante C Napolitano, LaDO IOUSP\n",
    "    #   dante.napolitano@usp.br (Jan 2018)\n",
    "    ################################################################\n",
    "    \"\"\"\n",
    "\n",
    "    ur_field = 0.5 * (ufield[:,:,:-1] + ufield[:,:,1:])\n",
    "    ur_field = ur_field[:,1:-1,:]\n",
    "    vr_field = 0.5 * (vfield[:,:-1,:] + vfield[:,1:,:])\n",
    "    vr_field = vr_field[:,:,1:-1]\n",
    "\n",
    "    wr_field = wfield[:,1:-1,1:-1]\n",
    "\n",
    "    return ur_field,vr_field,wr_field\n",
    "\n",
    "### FUNCTION TS2RHO_3D ##################################################\n",
    "def ts2rho_3d(tfield,sfield):\n",
    "\n",
    "    \"\"\"\n",
    "    ################################################################\n",
    "    #\n",
    "    #   adptation of the t,s matrices\n",
    "    #\n",
    "    #   Dante C Napolitano, LaDO IOUSP\n",
    "    #   dante.napolitano@usp.br (Jan 2018)\n",
    "    ################################################################\n",
    "    \"\"\"\n",
    "\n",
    "    tr_field = tfield[:,1:-1,1:-1]\n",
    "    sr_field = sfield[:,1:-1,1:-1]\n",
    "\n",
    "    return tr_field,sr_field\n",
    "\n",
    "### FUNCTION UNIQUE GRID ##################################################\n",
    "def unique_grid(prop):\n",
    "\n",
    "    \"\"\"\n",
    "    #################################################################\n",
    "    #\n",
    "    #   performs an adaption on \"rho_grid\" so all properties may share\n",
    "    #   the same lon, lat coordinates\n",
    "    #\n",
    "    #   Dante C Napolitano, LaDO IOUSP\n",
    "    #   dante.napolitano@usp.br (Jan 2018)\n",
    "    #################################################################\n",
    "    \"\"\"\n",
    "    return prop[1:-1,1:-1]\n",
    "\n",
    "### FUNCTION ZCOORDS #######################################################\n",
    "def zcoords(prop,z,znew):\n",
    "\n",
    "    DF = pd.DataFrame([],index=znew)\n",
    "    i,j,k = prop.shape\n",
    "    ct=0\n",
    "    for ri,zi in zip(prop.reshape(i,j*k).T,z.reshape(i,j*k).T):\n",
    "        df = pd.DataFrame(ri[::-1],index=zi[::-1],columns=[ct])\n",
    "        df = df.reindex(znew[znew<df.index.values[-1]],method='backfill',limit=1)\n",
    "        df = df.interpolate(limit_direction='backward')\n",
    "        DF = DF.join(df)\n",
    "        ct+=1\n",
    "\n",
    "    return np.reshape(DF.values,newshape=(len(znew),j,k))\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
